# Generated by Django 3.1 on 2020-08-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date publushed')),
            ],
        ),
    ]
