# Generated by Django 3.1 on 2020-09-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0004_auto_20200901_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
