# Generated by Django 3.1 on 2020-09-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_web', '0005_rename_answer_text_and_add_model_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ques',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                    to='covid_web.question'),
            preserve_default=False,
        ),
    ]
