# Generated by Django 3.1.2 on 2020-10-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0006_delete_answer_ques_add_question_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='password',
            field=models.TextField(default='0000'),
        ),
    ]
