# Generated by Django 3.1 on 2020-09-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0006_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
    ]
