# Generated by Django 3.1.2 on 2020-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_web', '0007_question_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('Area', models.TextField(null=True)),
                ('Total', models.TextField(null=True)),
                ('Cases', models.TextField(null=True)),
                ('Recovered', models.TextField(null=True)),
                ('Deaths', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'world_confirmation',
            },
        ),
    ]
