# Generated by Django 3.1 on 2020-09-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0007_auto_20200901_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
