# Generated by Django 3.1.2 on 2020-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_web', '0008_create_worldconfirmation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldconfirmation',
            name='Trends',
            field=models.TextField(null=True),
        ),
    ]
