# Generated by Django 3.1 on 2020-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0008_auto_20200901_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ques',
        ),
    ]
