# Generated by Django 3.1.2 on 2020-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_web', '0009_worldconfirmation_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('headline', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('time', models.TextField(null=True)),
                ('origin_url', models.TextField(null=True)),
                ('created_at', models.TextField(null=True)),
            ],
            options={
                'db_table': 'covid19_article',
            },
        ),
    ]
