# Generated by Django 3.1 on 2020-09-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_web', '0009_remove_answer_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Covid_web.question'),
            preserve_default=False,
        ),
    ]
